name: Release to GitHub

on:
  workflow_call:
    inputs:
      gh_tag:
        type: string
        required: true
        description: GitHub tag value
      artifact_name:
        type: string
        required: false
        description: Artifact name of the function app
        default: fncapp

jobs:
  deploy_github:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Extract version from tag
      shell: pwsh
      run: |
        $version = (echo ${{ inputs.gh_tag }}) -replace "refs/tags/", ""

        echo "RELEASE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Download Function app artifacts
      uses: actions/download-artifact@v3
      with:
        path: ${{ github.workspace }}/published

    - name: Zip Function app artifacts
      shell: pwsh
      run: |
        $version = "$env:RELEASE_VERSION"
        $destination_path = "published/fncapp-$($version).zip"

        Compress-Archive -Path published/${{ inputs.artifact_name }}/* -DestinationPath $destination_path

        echo "FNCAPP_PATH=$destination_path" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Release Function app artifacts to GitHub
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        name: Release ${{ env.RELEASE_VERSION }}
        generate_release_notes: true
        files: |
          ${{ env.FNCAPP_PATH }}
