name: Release to Azure

on:
  workflow_dispatch:
    inputs:
      resource_name:
        type: string
        required: true
        description: 'Azure resource name'

jobs:
  call_deployment_azure:
    uses: ./.github/workflows/deployment-azure.yaml
    secrets: inherit
    with:
      artifact_name: fncapp
      resource_name: ${{ github.event.inputs.resource_name }}
      resource_suffix: 'api'
      do_not_deploy: 'true'
